openapi: 3.0.0
info:
  title: Meet the heroes
  description: Servidor de Meet the heroes
  version: 1.0.0

servers:
  - url: http://localhost:8080/api/v1
    description: Local development server
  - url: https://meet-the-heroes.herokuapp.com/api/v1
    description: Development server

paths:
  /claps:
    get:
      summary: Returns the number of claps
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Clap'
        '5XX':
          $ref: "#/components/responses/UnexpectedError"

    put:
      summary: increment the clap count
      responses:
        '200':
          description: OK
        '5XX':
          $ref: "#/components/responses/UnexpectedError"

  /countries:
    get:
      summary: Returns the countries
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Filter'
        '5XX':
          $ref: "#/components/responses/UnexpectedError"
  
  /types:
    get:
      summary: Returns all types
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Filter'
        '5XX':
          $ref: "#/components/responses/UnexpectedError"

  /study/type:
    get:
      parameters:
        - in: query
          name: idType
          schema:
            type: integer
          description: The id of the study type
      summary: Returns studies by studyId
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Filter'
        '5XX':
          $ref: "#/components/responses/UnexpectedError"

produces:
  application/json
consumes:
  application/json

components:

  responses:
    MissingHeader:
      description: Missing Authorization Header
      headers:
        Authorization:
          schema:
            type: string
    InvalidAuthorizationHeader:
      description: Invalid Authentication Token
      headers:
        Authorization:
          schema:
            type: string
    UnauthorizedOperation:
      description: "Invalid Operation, e.g.: trying to access a protected endpoint"
      headers:
        Authorization:
          schema:
            type: string
    ResourceNotFound:
      description: Resource not found
      headers:
        Authorization:
          schema:
            type: string
    UnexpectedError:
      description: Server-side error without handling
    ValidationError:
      description: Validation errors
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
              validations:
                type: array
                items:
                  type: object
                  properties:
                    field:
                      type: string
                    message:
                      type: string
    NotAllowed:
      description: You have a pending request of such type
      headers:
        Authorization:
          schema:
            type: string
    BadRequest:
      description: Cannot downgrade a non distributor
      headers:
        Authorization:
          schema:
            type: string

  schemas:
    Clap:
      type: object
      properties:
        clapCount:
          type: number

    Filter:
      type: object
      properties:
        id:
          type: number
        name:
          type: string

  
